// Common Canadian passenger-vehicle makes and models, including popular
// current and recent discontinued models. Keep this local so Profile remains
// fast and usable without depending on a third-party vehicle-data service.
export const VEHICLE_MODELS = {
  Acura: ["CL", "CSX", "EL", "ILX", "Integra", "MDX", "NSX", "RDX", "RL", "RLX", "RSX", "TL", "TLX", "TSX", "ZDX"],
  "Alfa Romeo": ["4C", "Giulia", "Stelvio", "Tonale"],
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "e-tron GT", "Q3", "Q4 e-tron", "Q5", "Q6 e-tron", "Q7", "Q8", "R8", "S3", "S4", "S5", "S6", "S7", "S8", "TT"],
  Bentley: ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  BMW: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "i3", "i4", "i5", "i7", "i8", "iX", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z4"],
  Buick: ["Allure", "Cascada", "Enclave", "Encore", "Encore GX", "Envision", "Envista", "LaCrosse", "Lucerne", "Regal", "Verano"],
  Cadillac: ["ATS", "CT4", "CT5", "CT6", "CTS", "ELR", "Escalade", "LYRIQ", "OPTIQ", "SRX", "XT4", "XT5", "XT6", "XTS"],
  Chevrolet: ["Avalanche", "Aveo", "Blazer", "Bolt EUV", "Bolt EV", "Camaro", "Captiva", "Cobalt", "Colorado", "Corvette", "Cruze", "Equinox", "Express", "HHR", "Impala", "Malibu", "Monte Carlo", "Orlando", "Silverado 1500", "Silverado 2500HD", "Silverado 3500HD", "Sonic", "Spark", "Suburban", "Tahoe", "Trailblazer", "Traverse", "Trax", "Uplander", "Volt"],
  Chrysler: ["200", "300", "Aspen", "Crossfire", "Grand Caravan", "Pacifica", "PT Cruiser", "Sebring", "Town & Country", "Voyager"],
  Dodge: ["Avenger", "Caliber", "Caravan", "Challenger", "Charger", "Dakota", "Dart", "Durango", "Grand Caravan", "Hornet", "Journey", "Magnum", "Neon", "Nitro", "Ram 1500", "Viper"],
  Ferrari: ["296", "458", "488", "812", "California", "F8", "GTC4Lusso", "Portofino", "Purosangue", "Roma", "SF90"],
  FIAT: ["124 Spider", "500", "500L", "500X", "500e"],
  Ford: ["Bronco", "Bronco Sport", "C-Max", "Crown Victoria", "E-Series", "EcoSport", "Edge", "Escape", "Expedition", "Explorer", "F-150", "F-250", "F-350", "Fiesta", "Flex", "Focus", "Fusion", "Maverick", "Mustang", "Mustang Mach-E", "Ranger", "Taurus", "Transit", "Transit Connect"],
  Genesis: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  GMC: ["Acadia", "Canyon", "Envoy", "Hummer EV", "Savana", "Sierra 1500", "Sierra 2500HD", "Sierra 3500HD", "Terrain", "Yukon"],
  Honda: ["Accord", "Civic", "Clarity", "CR-V", "CR-Z", "Crosstour", "Element", "Fit", "HR-V", "Insight", "Odyssey", "Passport", "Pilot", "Prelude", "Prologue", "Ridgeline", "S2000"],
  Hummer: ["H1", "H2", "H3"],
  Hyundai: ["Accent", "Azera", "Elantra", "Entourage", "Equus", "Genesis", "Ioniq", "Ioniq 5", "Ioniq 6", "Kona", "Nexo", "Palisade", "Santa Cruz", "Santa Fe", "Sonata", "Tiburon", "Tucson", "Veloster", "Venue", "Veracruz"],
  INFINITI: ["EX", "FX", "G", "JX", "M", "Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX56", "QX60", "QX70", "QX80"],
  Jaguar: ["E-PACE", "F-PACE", "F-TYPE", "I-PACE", "S-TYPE", "X-TYPE", "XE", "XF", "XJ", "XK"],
  Jeep: ["Cherokee", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Grand Wagoneer", "Liberty", "Patriot", "Renegade", "Wagoneer", "Wrangler"],
  Kia: ["Amanti", "Borrego", "Cadenza", "Carnival", "EV6", "EV9", "Forte", "K4", "K5", "K900", "Magentis", "Niro", "Optima", "Rio", "Rondo", "Sedona", "Seltos", "Sorento", "Soul", "Spectra", "Sportage", "Stinger", "Telluride"],
  Lamborghini: ["Aventador", "Gallardo", "Huracan", "Revuelto", "Urus"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "LR2", "LR3", "LR4", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  Lexus: ["CT", "ES", "GS", "GX", "HS", "IS", "LC", "LFA", "LS", "LX", "NX", "RC", "RX", "RZ", "SC", "TX", "UX"],
  Lincoln: ["Aviator", "Corsair", "MKC", "MKS", "MKT", "MKX", "MKZ", "Nautilus", "Navigator", "Town Car", "Zephyr"],
  Lucid: ["Air", "Gravity"],
  Maserati: ["Ghibli", "GranCabrio", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  Mazda: ["CX-3", "CX-30", "CX-5", "CX-50", "CX-7", "CX-70", "CX-9", "CX-90", "Mazda2", "Mazda3", "Mazda5", "Mazda6", "MX-30", "MX-5 Miata", "RX-8", "Tribute"],
  "Mercedes-Benz": ["A-Class", "AMG GT", "B-Class", "C-Class", "CLA", "CLE", "CLK", "CLS", "E-Class", "EQA", "EQB", "EQE", "EQS", "G-Class", "GL", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "M-Class", "R-Class", "S-Class", "SL", "SLC", "SLK", "Sprinter"],
  Mercury: ["Grand Marquis", "Mariner", "Milan", "Montego", "Monterey", "Mountaineer", "Sable"],
  MINI: ["Clubman", "Convertible", "Cooper", "Countryman", "Coupe", "Hardtop", "Paceman", "Roadster"],
  Mitsubishi: ["Eclipse", "Eclipse Cross", "Endeavor", "Galant", "Lancer", "Mirage", "Montero", "Outlander", "Outlander PHEV", "RVR"],
  Nissan: ["350Z", "370Z", "Altima", "ARIYA", "Armada", "Cube", "Frontier", "GT-R", "Juke", "Kicks", "LEAF", "Maxima", "Micra", "Murano", "NV", "Pathfinder", "Qashqai", "Rogue", "Sentra", "Titan", "Versa", "Xterra", "Z"],
  Oldsmobile: ["Alero", "Aurora", "Bravada", "Intrigue", "Silhouette"],
  Polestar: ["1", "2", "3", "4"],
  Pontiac: ["Aztek", "G3", "G5", "G6", "G8", "Grand Am", "Grand Prix", "Montana", "Solstice", "Sunfire", "Torrent", "Vibe"],
  Porsche: ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  Ram: ["1500", "2500", "3500", "ProMaster", "ProMaster City"],
  Rivian: ["R1S", "R1T"],
  Saab: ["9-2X", "9-3", "9-5", "9-7X"],
  Saturn: ["Astra", "Aura", "ION", "Outlook", "Relay", "Sky", "VUE"],
  Scion: ["FR-S", "iM", "iQ", "tC", "xA", "xB", "xD"],
  smart: ["fortwo"],
  Subaru: ["Ascent", "B9 Tribeca", "BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Outback", "Solterra", "Tribeca", "WRX", "XV Crosstrek"],
  Suzuki: ["Equator", "Grand Vitara", "Kizashi", "SX4", "Swift", "Verona", "Vitara", "XL7"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  Toyota: ["4Runner", "Avalon", "bZ4X", "C-HR", "Camry", "Celica", "Corolla", "Corolla Cross", "Crown", "FJ Cruiser", "GR86", "Grand Highlander", "Highlander", "Land Cruiser", "Matrix", "Mirai", "Prius", "RAV4", "Sequoia", "Sienna", "Solara", "Supra", "Tacoma", "Tundra", "Venza", "Yaris"],
  Volkswagen: ["Arteon", "Atlas", "Atlas Cross Sport", "Beetle", "CC", "Eos", "Golf", "Golf GTI", "Golf R", "ID.4", "ID. Buzz", "Jetta", "Passat", "Rabbit", "Taos", "Tiguan", "Touareg"],
  Volvo: ["C30", "C40 Recharge", "EX30", "EX40", "EX90", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"],
  Other: ["Other / not listed"],
};

export const VEHICLE_MAKES = Object.keys(VEHICLE_MODELS);

export const VEHICLE_COLOURS = [
  "Black", "White", "Silver", "Grey", "Blue", "Red", "Green", "Brown",
  "Beige", "Gold", "Yellow", "Orange", "Purple", "Burgundy", "Other",
];

