-- ParkShare organizer event-submission review queue
-- Run once in Supabase SQL Editor before deploying api/submit-event.js.

create table if not exists public.event_submissions (
  id bigint generated by default as identity primary key,
  status text not null default 'pending'
    check (status in ('pending', 'reviewing', 'approved', 'rejected')),
  organizer_name text not null,
  organizer_email text not null,
  organizer_phone text,
  event_name text not null,
  category text not null
    check (category in ('concert', 'sports', 'festival', 'theatre', 'community')),
  venue_name text not null,
  address text not null,
  event_date date not null,
  start_time time not null,
  end_time time,
  description text not null,
  ticket_url text,
  event_url text,
  access_notes text,
  submitted_from text not null default 'discover',
  reviewer_notes text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists event_submissions_review_queue_idx
  on public.event_submissions (status, created_at desc);

alter table public.event_submissions enable row level security;

-- No browser-facing read, insert, update, or delete policies are created.
-- api/submit-event.js uses the Supabase service role to accept validated
-- submissions. Only trusted ParkShare staff/service processes can review the
-- queue or copy a verified submission into public.events.

