-- ParkShare event-parking discovery
-- Run this migration in the Supabase SQL Editor before deploying the matching
-- application/API files. Event rows are read publicly; writes remain limited
-- to the Supabase service role or dashboard until an organizer review flow is
-- introduced.

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  source text not null default 'ParkShare',
  source_event_id text,
  name text not null,
  category text not null default 'community'
    check (category in ('concert', 'sports', 'festival', 'theatre', 'community')),
  venue_name text,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  timezone text not null default 'America/Toronto',
  status text not null default 'draft'
    check (status in ('draft', 'published', 'cancelled', 'postponed')),
  source_url text,
  image_url text,
  access_notes text,
  closure_notice text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_end_after_start check (ends_at is null or ends_at > starts_at),
  constraint events_source_identity unique (source, source_event_id)
);

create index if not exists events_published_starts_at_idx
  on public.events (starts_at)
  where status = 'published';

create index if not exists events_location_idx
  on public.events (lat, lng)
  where status = 'published';

alter table public.events enable row level security;

drop policy if exists "Published events are publicly readable" on public.events;
create policy "Published events are publicly readable"
  on public.events
  for select
  to anon, authenticated
  using (status = 'published');

-- Event-specific access review. A listing marked "blocked" is removed from
-- that event's parking results; "warning" remains bookable with a clear note.
create table if not exists public.event_listing_access (
  event_id bigint not null references public.events(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  access_status text not null default 'warning'
    check (access_status in ('available', 'warning', 'blocked')),
  notes text,
  verified_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (event_id, listing_id)
);

alter table public.event_listing_access enable row level security;

drop policy if exists "Event listing access is publicly readable" on public.event_listing_access;
create policy "Event listing access is publicly readable"
  on public.event_listing_access
  for select
  to anon, authenticated
  using (true);

-- A reservation keeps a minimal event snapshot so both the Driver and Host
-- can still understand what the parking was for if a provider later changes
-- or removes the source event. Only store snapshots permitted by the event
-- provider's commercial licence.
alter table public.bookings add column if not exists event_id bigint references public.events(id) on delete set null;
alter table public.bookings add column if not exists event_name text;
alter table public.bookings add column if not exists event_category text;
alter table public.bookings add column if not exists event_venue_name text;
alter table public.bookings add column if not exists event_address text;
alter table public.bookings add column if not exists event_lat double precision;
alter table public.bookings add column if not exists event_lng double precision;
alter table public.bookings add column if not exists event_starts_at timestamptz;
alter table public.bookings add column if not exists event_ends_at timestamptz;
alter table public.bookings add column if not exists event_timezone text;
alter table public.bookings add column if not exists event_source text;
alter table public.bookings add column if not exists event_source_url text;
alter table public.bookings add column if not exists event_access_notes text;
alter table public.bookings add column if not exists event_closure_notice text;

create index if not exists bookings_event_id_idx on public.bookings(event_id);

-- Optional test event template. Replace every placeholder with verified,
-- licensed information before removing the leading comment markers.
-- insert into public.events (
--   source, source_event_id, name, category, venue_name, address, lat, lng,
--   starts_at, ends_at, timezone, status, source_url, access_notes, closure_notice
-- ) values (
--   'ParkShare organizer submission', 'replace-me', 'Verified event name',
--   'festival', 'Verified venue', 'Verified address', 43.8561, -79.5085,
--   '2026-09-12T16:00:00Z', '2026-09-13T00:00:00Z', 'America/Toronto',
--   'published', 'https://example.com/verified-event',
--   'Use the signed festival entrance.', 'Review event-day road closures.'
-- );
